module Sauna.Preprocessed where

import Sauna.Data.Word (Word(Word))
import Data.Quintuple (Quintuple(Quintuple))
import Sauna.Data.Letter (Letter(..))
import Sauna.Data.Color (Color(..))
import Sauna.Data.Response (Response(Response))


import Sauna.Data.State (State(State))
import Text.Read (read)
import Data.Maybe (Maybe(Just, Nothing))
import Data.Function (($))
import Prelude (undefined)


preprocessed :: State -> Maybe Word
-- Level One
preprocessed (State []) = Just (read "OIETA")
-- Level Two
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Yellow,Yellow)))]) = Just $ Word $ Quintuple (K,A,R,S,I) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Yellow,Green)))]) = Just $ Word $ Quintuple (K,E,R,M,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (H,A,P,A,N) -- 9))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Green,Green)))]) = Just $ Word $ Quintuple (L,A,S,K,U) -- 8))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (M,U,T,R,U) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (N,E,U,L,E) -- 14))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Green,Black)))]) = Just $ Word $ Quintuple (N,Ö,Y,R,Ä) -- 7))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Black,Black)))]) = Just $ Word $ Quintuple (L,Ä,K,S,Y) -- 14))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (K,A,L,H,U) -- 9))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (K,Ä,R,E,Ä) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (T,A,R,K,E) -- 8))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (K,A,T,O,S) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (T,Y,L,S,Ä) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (K,U,P,R,U) -- 11))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (P,Y,S,Y,Ä) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Black,Green)))]) = Just $ Word $ Quintuple (K,R,A,P,U) -- 35))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Green,Yellow)))]) = Just $ Word $ Quintuple (A,V,A,U,S) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Black,Green)))]) = Just $ Word $ Quintuple (A,M,B,R,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Green,Green)))]) = Just $ Word $ Quintuple (A,S,K,A,R) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Black,Yellow)))]) = Just $ Word $ Quintuple (A,J,E,L,U) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Black,Black)))]) = Just $ Word $ Quintuple (A,L,U,K,E) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Yellow,Black)))]) = Just $ Word $ Quintuple (E,L,Ä,K,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Green,Black)))]) = Just $ Word $ Quintuple (E,H,K,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Green,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Black,Green)))]) = Just $ Word $ Quintuple (M,A,I,N,E) -- 6))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,P,E,U,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (L,I,T,S,I) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (K,U,T,E,N) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (K,A,L,S,A) -- 23))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Black,Black)))]) = Just $ Word $ Quintuple (R,U,K,S,I) -- 23))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (K,Y,R,S,Ä) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Green,Black)))]) = Just $ Word $ Quintuple (E,H,T,Y,Ä) -- 7))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (H,A,P,A,N) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (H,I,T,S,I) -- 7))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,H,A,V,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,P,I,L,A) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (P,R,I,K,I) -- 10))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (H,I,R,S,I) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Green,Green)))]) = Just $ Word $ Quintuple (K,A,L,P,A) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (K,E,L,S,I) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Green,Yellow)))]) = Just $ Word $ Quintuple (C,H,I,L,I) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Green,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,R,N,I) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,T,O) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Green,Black,Black)))]) = Just $ Word $ Quintuple (B,E,E,S,I) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (L,Ä,S,K,I) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Black,Black)))]) = Just $ Word $ Quintuple (S,K,I,N,I) -- 16))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (K,U,T,R,I) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,R,M,A,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,S,K,E,L) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Black,Green)))]) = Just $ Word $ Quintuple (P,R,I,K,I) -- 21))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Green,Black)))]) = Just $ Word $ Quintuple (H,I,S,S,I) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (A,H,D,I,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,L,I,E,N) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (H,Ö,N,K,Ä) -- 6))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (A,H,D,A,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (S,Y,D,Ä,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (L,I,I,R,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Black,Black)))]) = Just $ Word $ Quintuple (L,U,K,S,I) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Black,Green)))]) = Just $ Word $ Quintuple (N,I,R,S,O) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Green,Black)))]) = Just $ Word $ Quintuple (E,L,P,Y,Ä) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (K,E,H,N,O) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (K,O,P,S,U) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Black,Black)))]) = Just $ Word $ Quintuple (K,U,P,R,U) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (H,A,L,K,O) -- 10))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Green,Black)))]) = Just $ Word $ Quintuple (J,U,O,R,U) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Black,Green)))]) = Just $ Word $ Quintuple (L,U,K,S,I) -- 15))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (K,U,T,S,U) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (H,E,L,K,E) -- 8))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Green,Green)))]) = Just $ Word $ Quintuple (H,U,T,S,U) -- 5))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,S,K,E,L) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (I,N,T,R,O) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Green,Green)))]) = Just $ Word $ Quintuple (A,A,R,I,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Black,Black)))]) = Just $ Word $ Quintuple (A,H,A,V,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,T,O,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (L,A,N,K,O) -- 4))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Black,Black)))]) = Just $ Word $ Quintuple (L,O,K,U,M) -- 19))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (K,A,L,V,I) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Black,Green)))]) = Just $ Word $ Quintuple (V,A,R,I,S) -- 3))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Green,Black)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (D,E,K,K,I) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (N,O,R,M,I) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,H,K,I,O) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Green,Black)))]) = Just $ Word $ Quintuple (K,U,M,P,I) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (A,R,M,A,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Black,Black)))]) = Just $ Word $ Quintuple (S,K,O,O,L) -- 6))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Black,Green)))]) = Just $ Word $ Quintuple (A,R,P,O,A) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (D,E,P,I,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,H,D,A,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,I,R,O,T) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (A,H,N,A,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Green,Black)))]) = Just $ Word $ Quintuple (K,I,I,S,U) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,H,A,V,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Green,Black,Black)))]) = Just $ Word $ Quintuple (H,A,L,K,I) -- 2))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Green,Green,Black)))]) = Just $ Word $ Quintuple (A,M,M,U,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (A,H,N,A,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Black,Black)))]) = Just $ Word $ Quintuple (H,O,U,R,U) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Green,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,M,M,U,S) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Black,Green)))]) = Just $ Word $ Quintuple (B,A,M,B,U) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Green,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Green,Black,Green)))]) = Just $ Word $ Quintuple (A,H,A,V,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Black,Black)))]) = Just $ Word $ Quintuple (C,H,I,L,I) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (B,A,A,R,I) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Black,Green)))]) = Just $ Word $ Quintuple (A,L,K,A,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (A,H,K,I,O) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Black,Green)))]) = Just $ Word $ Quintuple (A,A,M,E,N) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,R,I,A) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E) -- 1))
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),_)]) = undefined
-- The rest
preprocessed _ = Nothing


