module Sauna.Preprocessed where

import Sauna.Data.Word (Word(Word))
import Data.Quintuple (Quintuple(Quintuple))
import Sauna.Data.Letter (Letter(..))
import Sauna.Data.Color (Color(..))
import Sauna.Data.Response (Response(Response))
import Sauna.Data.State (State(State))
import Data.Maybe (Maybe(Just, Nothing))
import Data.Function (($))
import Prelude (undefined)


-- | Return preprocessed guess for given State.
-- Generated with:
--  main :: IO ()
--  main = do
--    let
--      states = [State [(fromJust $ preprocessed initialize, response)] |response <- [Response (Quintuple (x1,x2,x3,x4,x5)) | x1 <- [Black ..], x2 <- [Black ..],x3 <- [Black ..],x4 <- [Black ..],x5 <- [Black ..]]]
--      level2 = [minimumBy (\a b -> compare (snd a) (snd b)) (fmap (\word -> (word, eliminationScore state word)) (unwrap fullDictionary)) | state <- states]
--    parallel_ ((
--        \x -> do
--          print x
--          hFlush stdout
--       ) <$> zip states level2)
--    stopGlobalPool
preprocessed :: State -> Maybe Word
-- Level One
preprocessed (State []) = Just $ Word $ Quintuple(O,I,E,T,A)
-- Level Two
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Yellow,Yellow)))]) = Just $ Word $ Quintuple (K,A,R,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Yellow,Green)))]) = Just $ Word $ Quintuple (K,E,R,M,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (H,A,P,A,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Green,Green)))]) = Just $ Word $ Quintuple (L,A,S,K,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (M,U,T,R,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (N,E,U,L,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Green,Black)))]) = Just $ Word $ Quintuple (N,Ö,Y,R,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Black,Black)))]) = Just $ Word $ Quintuple (L,Ä,K,S,Y)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (K,A,L,H,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (K,Ä,R,E,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (T,A,R,K,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (K,A,T,O,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (T,Y,L,S,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (K,U,P,R,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (P,Y,S,Y,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Black,Black,Green)))]) = Just $ Word $ Quintuple (K,R,A,P,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Green,Yellow)))]) = Just $ Word $ Quintuple (A,V,A,U,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Black,Green)))]) = Just $ Word $ Quintuple (A,M,B,R,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Yellow,Green,Green)))]) = Just $ Word $ Quintuple (A,S,K,A,R)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Black,Yellow)))]) = Just $ Word $ Quintuple (A,J,E,L,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Black,Black)))]) = Just $ Word $ Quintuple (A,L,U,K,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Yellow,Black)))]) = Just $ Word $ Quintuple (E,L,Ä,K,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Green,Black)))]) = Just $ Word $ Quintuple (E,H,K,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Green,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Black,Green)))]) = Just $ Word $ Quintuple (M,A,I,N,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Black,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,P,E,U,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (L,I,T,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (K,U,T,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (K,A,L,S,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Black,Black)))]) = Just $ Word $ Quintuple (R,U,K,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (K,Y,R,S,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Green,Black)))]) = Just $ Word $ Quintuple (E,H,T,Y,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (H,A,P,A,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (H,I,T,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,H,A,V,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,P,I,L,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (P,R,I,K,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (H,I,R,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Black,Green,Green)))]) = Just $ Word $ Quintuple (K,A,L,P,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (K,E,L,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Green,Yellow)))]) = Just $ Word $ Quintuple (C,H,I,L,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Green,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,R,N,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Yellow,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,T,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Yellow,Green,Black,Black)))]) = Just $ Word $ Quintuple (B,E,E,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (L,Ä,S,K,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Black,Black)))]) = Just $ Word $ Quintuple (S,K,I,N,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (K,U,T,R,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,R,M,A,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,S,K,E,L)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Black,Green)))]) = Just $ Word $ Quintuple (P,R,I,K,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Green,Black)))]) = Just $ Word $ Quintuple (H,I,S,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (A,H,D,I,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,L,I,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (H,Ö,N,K,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (A,H,D,A,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (S,Y,D,Ä,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (L,I,I,R,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Black,Black)))]) = Just $ Word $ Quintuple (L,U,K,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Black,Green)))]) = Just $ Word $ Quintuple (N,I,R,S,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Green,Black)))]) = Just $ Word $ Quintuple (E,L,P,Y,Ä)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Black,Green,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (K,E,H,N,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (K,O,P,S,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Black,Black)))]) = Just $ Word $ Quintuple (K,U,P,R,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (H,A,L,K,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Green,Black)))]) = Just $ Word $ Quintuple (J,U,O,R,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Black,Green)))]) = Just $ Word $ Quintuple (L,U,K,S,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (K,U,T,S,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (H,E,L,K,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Black,Green,Green)))]) = Just $ Word $ Quintuple (H,U,T,S,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,S,K,E,L)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (I,N,T,R,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Green,Green)))]) = Just $ Word $ Quintuple (A,A,R,I,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Black,Black)))]) = Just $ Word $ Quintuple (A,H,A,V,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,T,O,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (L,A,N,K,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Black,Black)))]) = Just $ Word $ Quintuple (L,O,K,U,M)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (K,A,L,V,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Black,Green)))]) = Just $ Word $ Quintuple (V,A,R,I,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Black,Green,Green,Black)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (D,E,K,K,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (N,O,R,M,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,H,K,I,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Green,Black)))]) = Just $ Word $ Quintuple (K,U,M,P,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Black,Green,Yellow)))]) = Just $ Word $ Quintuple (A,R,M,A,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Yellow,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Yellow,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Black,Black)))]) = Just $ Word $ Quintuple (S,K,O,O,L)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Black,Green)))]) = Just $ Word $ Quintuple (A,R,P,O,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (D,E,P,I,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,H,D,A,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Yellow,Yellow)))]) = Just $ Word $ Quintuple (A,I,R,O,T)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (A,H,N,A,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Green,Black)))]) = Just $ Word $ Quintuple (K,I,I,S,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,H,A,V,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Green,Black,Black)))]) = Just $ Word $ Quintuple (H,A,L,K,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Yellow,Green,Green,Green,Black)))]) = Just $ Word $ Quintuple (A,M,M,U,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Yellow,Green)))]) = Just $ Word $ Quintuple (A,H,N,A,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Black,Black)))]) = Just $ Word $ Quintuple (H,O,U,R,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Green,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Green,Green)))]) = Just $ Word $ Quintuple (A,M,M,U,S)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Black,Black,Green)))]) = Just $ Word $ Quintuple (B,A,M,B,U)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Green,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Green,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Green,Black,Green)))]) = Just $ Word $ Quintuple (A,H,A,V,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Black,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Black,Black)))]) = Just $ Word $ Quintuple (C,H,I,L,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (B,A,A,R,I)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Black,Green)))]) = Just $ Word $ Quintuple (A,L,K,A,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Yellow,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (A,H,K,I,O)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Black,Green)))]) = Just $ Word $ Quintuple (A,A,M,E,N)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Yellow,Black)))]) = Just $ Word $ Quintuple (A,A,R,I,A)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Black,Black)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Black,Black,Yellow)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Yellow,Black,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),Response(Quintuple(Green,Green,Green,Green,Green)))]) = Just $ Word $ Quintuple (A,A,L,O,E)
preprocessed (State [(Word(Quintuple(O,I,E,T,A)),_)]) = undefined
-- The rest
preprocessed _ = Nothing


